from __future__ import annotations

import csv
import json
from pathlib import Path

from engine.omnicircuit.models import AnalysisResult


def write_outputs(project_root: Path, analysis: AnalysisResult) -> None:
    output_dir = project_root / "outputs" / analysis.project_id
    manufacturing_dir = output_dir / "manufacturing"
    assets_dir = project_root / "assets" / "generated"

    manufacturing_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)

    (output_dir / "AI_DESIGN_REPORT.md").write_text(_design_report(analysis), encoding="utf-8")
    (output_dir / "VALIDATION_REPORT.md").write_text(_validation_report(analysis), encoding="utf-8")
    (manufacturing_dir / "README.md").write_text(_manufacturing_readme(), encoding="utf-8")
    _write_cpl_placeholder(manufacturing_dir / "CPL_PLACEHOLDER.csv")
    _write_bom_handoff(project_root / "BOM.csv", manufacturing_dir / "BOM_PCBA.csv")
    (assets_dir / "uwb_anchor_analysis.json").write_text(
        json.dumps(analysis.to_dict(), indent=2),
        encoding="utf-8",
    )


def _design_report(analysis: AnalysisResult) -> str:
    passed = sum(1 for check in analysis.checks if check.status == "pass")
    body = [
        f"# {analysis.project_name} AI Design Report",
        "",
        f"- Generated: {analysis.generated_at}",
        f"- Overall status: {analysis.overall_status}",
        f"- Validation checks passed: {passed}/{len(analysis.checks)}",
        "",
        "## Design Intent",
        "",
        "This proof-of-concept pipeline converts the UWB anchor source package into a deterministic rule model. "
        "The next exporter stage should bind these constraints to KiCad board, schematic, netclass, and fabrication outputs.",
        "",
        "## Critical Constraints",
        "",
    ]
    for check in analysis.checks:
        body.extend(
            [
                f"### {check.category}: {check.requirement}",
                "",
                f"- Status: {check.status}",
                f"- Evidence: {check.evidence}",
                f"- Next action: {check.recommendation}",
                "",
            ]
        )
    return "\n".join(body)


def _validation_report(analysis: AnalysisResult) -> str:
    rows = [
        "# Validation Report",
        "",
        "| Category | Requirement | Status | Evidence |",
        "| --- | --- | --- | --- |",
    ]
    for check in analysis.checks:
        rows.append(
            f"| {check.category} | {check.requirement} | {check.status} | {check.evidence} |"
        )
    rows.extend(
        [
            "",
            "## Required Human Review",
            "",
            "- RF impedance must be verified in the final PCB tool using the actual manufacturer stackup.",
            "- AC isolation must be inspected by an electronics engineer before fabrication.",
            "- Gerber, drill, CPL, and assembly exports are scaffolded in this proof of concept and must be generated by a PCB CAD exporter before ordering.",
        ]
    )
    return "\n".join(rows)


def _manufacturing_readme() -> str:
    return "\n".join(
        [
            "# Manufacturing Handoff",
            "",
            "This directory is the PCBWay-compatible output target.",
            "",
            "Expected final files:",
            "",
            "- `gerbers.zip`: Gerber and drill package.",
            "- `BOM_PCBA.csv`: Assembly bill of materials.",
            "- `CPL_PLACEHOLDER.csv`: Pick and place file to be replaced by PCB CAD export.",
            "- Assembly drawings: top, bottom, and 3D render.",
            "- Fabrication drawing: board outline, stackup, tolerances, materials, and controlled impedance notes.",
            "",
            "The current proof of concept intentionally does not claim fabrication readiness until a KiCad/PCBai exporter produces geometry and DRC/ERC pass artifacts.",
        ]
    )


def _write_cpl_placeholder(path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as cpl_file:
        writer = csv.writer(cpl_file)
        writer.writerow(["Designator", "Mid X", "Mid Y", "Layer", "Rotation", "Comment"])
        writer.writerow(["U2", "TBD", "TBD", "Top", "TBD", "DWM3000 placement locked by RF and RTLS constraints"])
        writer.writerow(["J2", "TBD", "TBD", "Top", "TBD", "SMA placement locked to RF edge launch"])


def _write_bom_handoff(source: Path, destination: Path) -> None:
    destination.write_text(source.read_text(encoding="utf-8"), encoding="utf-8")
